# Numpy2

In [1]:
import numpy as np

In [3]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
mx_is = np.ones(3)
print(mx_is)

[1. 1. 1.]


In [8]:
mx_is.dtype

dtype('float64')

In [9]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
mx_0s = np.zeros((4,6), dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [13]:
mx_0s = np.zeros((4,6), dtype = str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [14]:
mx_str = ''
print(bool(mx_str))

False


In [15]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.34777768e-321]
 [8.45593933e-307 9.34600962e-307 1.29060870e-306]]
